"use client";
import { Poppins, Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";
import Animate from "@/components/animate";
import { ClerkProvider } from "@clerk/nextjs";
import Head from "next/head";

const header = Poppins({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-header",
});

const body = Inter({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-body",
});

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>SiteGenie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={twMerge("min-h-screen bg-background", body.className)}
          >
            {children}
          </body>
        </html>
      </ClerkProvider>
    </>
  );
}
